runtime: python
env: flex

# Use a special gunicorn worker class to support websockets.
entrypoint: gunicorn  -b :$PORT --worker-class eventlet -w 1 main:app

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1

network:
  session_affinity: true